### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dakotacsk**

### CODE REVIEW

**Comment by dakotacsk** [comment]
I'm checking on behalf of student government on whether we can edit this. Do you know who has write access and whether that can be transferred to a current student?

**Comment by VagueSalutations** [comment]
Hi Dakota, thanks for reaching out!  Yes, most recently (as of June 20, 2023), Isabella Abilheira has write access, but I can also give you write access directly.  Send me an email at bohATalumni.olin.edu and I can send you credentials.

**Comment by EarlJr53** [comment]
@VagueSalutations Do you know who is the actual owner/who hosts the site? I know that myself and @cmccurley22 are the 2 current students with write access, but I'm not sure who actually owns the domain and the repo, etc.

**Comment by VagueSalutations** [comment]
@EarlJr53, our build domain was set up by alum Evan New-Schmidt while he was a library NINJA in 2018, so I believe the Olin Library owns/hosts the Olin.build subdomain.

The domain simply points at this repo, which is owned by a dedicated GitHub account and associated gmail account which maintainers (like you) have the login credentials for.

**Pull request closed without merging**
